#=======================================================================
#
#               .oooooo..o oooooo     oooo ooooooo  ooooo     
#              d8P'    `Y8  `888.     .8'   `8888    d8'      
#              Y88bo.        `888.   .8'      Y888..8P        
#               `"Y8888o.     `888. .8'        `8888'         
#                   `"Y88b     `888.8'        .8PY888.        
#              oo     .d8P      `888'        d8'  `888b       
#              8""88888P'        `8'       o888o  o88888o
#
#                  SystemVerilog Extension Library
#
#
# Copyright 2016 NVIDIA Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#=======================================================================

#-----------------------------------------------------------------------
#
# Test Makefile
#
# Makefile for building and running the SVX test suite
#-----------------------------------------------------------------------

TEST		:= test

COMPILELOG	:= compile.log
VCSLOG		:= vcs.log

VCS 		:= vcs 

SVX_SRC		:= ../src/svx.sv
SVUNIT_SRC	:= ${SVUNIT_INSTALL}/svunit_base/svunit_pkg.sv

UNIT_TESTS      := ${wildcard */*_unit_test.sv}
TESTSUITES      := ${wildcard */*_testsuite.sv}

APPS		:= ../apps
APPS_SRC	:= ${wildcard ${APPS}/mem/*.sv}             \
                   ${wildcard ${APPS}/mem_map/*.sv}

APPS_INC	:= +incdir+${APPS}/mem                      \
                   +incdir+${APPS}/mem_map

SRC		= test_utils.sv                             \
                  ${SVUNIT_SRC}                             \
                  ${SVX_SRC}                                \
                  ${APPS_SRC}                               \
                  ${UNIT_TESTS}                             \
                  ${TESTSUITES}                             \
                  testrunner.sv

INC		= +incdir+.                                 \
                  +incdir+${SVUNIT_INSTALL}/svunit_base     \
                  +incdir+../src                            \
                  ${APPS_INC}

COMPILE_OPTS    = +vcs+lic+wait                             \
                  +libext+.v                                \
                  +libext+.sv                               \
                  -sverilog                                 \
                  -debug                                    \
                  -timescale=1ns/1ps                        \
                  -debug_access+all -lca

VERDI_OPTS	= -2012 -vcs simv


VCS_CMD		= ${INC} ${SRC} ${COMPILE_OPTS} -l ${COMPILELOG}

VERDI_CMD	= verdi ${INC} ${SRC} ${COMPILE_OPTS} ${VERDI_OPTS}

RUN_OPTS	= 

SIMV		= ./simv -l ${VCSLOG} ${RUN_OPTS}


all: compile run

compile: ${SRC}
	${VCS} ${VCS_CMD}

run: 
	${SIMV}

verdi:
	${VERDI_CMD}

clean:
	rm -f ${COMPILELOG} ${VCSLOG} *.log
	rm -rf csrc simv.daidir vcdplus.vpd DVEfiles
	rm -f simv ucli.key vc_hdrs.h
	rm -f novas.*
	rm -f xx* *~ #*
